# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=500)),
                ('rec_date', models.DateTimeField(verbose_name='recorded')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='healthdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealth.Person'),
        ),
    ]
