# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(max_length=8, verbose_name='date of birth'),
        ),
    ]
