# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0003_auto_20181001_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date(2018, 10, 1), verbose_name='date of birth'),
        ),
    ]
