# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0004_auto_20181001_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 11, 15, 12, 934920, tzinfo=utc), verbose_name='date of birth'),
        ),
    ]
