# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0005_auto_20181001_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
    ]
