# Generated by Django 2.1.2 on 2018-10-08 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0006_auto_20181001_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='rec_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
    ]
