# Generated by Django 2.1.2 on 2018-10-08 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0007_auto_20181008_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
    ]
