# Generated by Django 2.1.2 on 2018-10-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0008_auto_20181008_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdata',
            old_name='data',
            new_name='heartrate',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='spo2',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='temp',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
